/**
 * Schemas for the content repository format (see docs/content-format.md).
 *
 * Every JSON file in a content repository is validated against one of these schemas when it is loaded.
 * JSON Schema versions for editor autocompletion are generated into content/schema/ by
 * `bun run content:schema`.
 */
import { z } from 'zod';

export const CONTENT_SCHEMA_VERSION = 1;

const id = z
  .string()
  .regex(/^[a-z0-9][a-z0-9-]*$/, 'ids are lowercase letters, digits and hyphens')
  .describe('Stable identifier (lowercase, digits, hyphens).');

const relPath = z
  .string()
  .min(1)
  .refine((p) => !p.startsWith('/') && !p.includes('\\') && !/^[a-z]+:/i.test(p), 'must be a relative path')
  .describe('Path relative to the file that references it.');

const hexColor = z.string().regex(/^#[0-9a-fA-F]{6}$/, 'colors are #rrggbb');

const yearMonth = z
  .string()
  .regex(/^\d{4}(-\d{2})?$/, 'dates are YYYY or YYYY-MM')
  .describe('Release date as YYYY or YYYY-MM.');

/** Text that may contain **bold** and *italic* markers; nothing else is interpreted. */
const richText = z.string().describe('Plain text; **bold** and *italic* markers are supported.');

// ---------------------------------------------------------------------------------------------------------------
// manifest.json
// ---------------------------------------------------------------------------------------------------------------

export const manifestFileSchema = z.object({
  path: relPath,
  size: z.number().int().nonnegative(),
  sha256: z.string().regex(/^[0-9a-f]{64}$/),
});

export const manifestSchema = z
  .object({
    $schema: z.string().optional(),
    schemaVersion: z.literal(CONTENT_SCHEMA_VERSION),
    name: z.string().min(1),
    description: z.string().optional(),
    homepage: z.url().optional(),
    games: z
      .array(z.object({ id, path: relPath }))
      .min(1)
      .describe('Entry points: one game.json per game system.'),
    files: z
      .array(manifestFileSchema)
      .describe(
        'Every file in the content tree. Generated by `bun run content:manifest`; do not edit by hand.',
      ),
  })
  .describe('Root index of a content repository.');

// ---------------------------------------------------------------------------------------------------------------
// theme.json
// ---------------------------------------------------------------------------------------------------------------

export const fontSchema = z.object({
  family: z.string().min(1).describe('Family name exactly as stored in the font files.'),
  files: z.array(relPath).min(1),
});

export const paletteSchema = z.object({
  background: hexColor.describe('Poster background.'),
  ink: hexColor.describe('Main text and line color.'),
  muted: hexColor.describe('Secondary text color.'),
  cardFill: hexColor.describe('Fill behind class cards (ignored when the background is transparent).'),
  bannerFill: hexColor.describe('Fill of section banners.'),
  bannerInk: hexColor.describe('Text color on section banners.'),
  accent: hexColor.describe('Highlight color (playtest badges and similar).'),
});

export const themeSchema = z.object({
  $schema: z.string().optional(),
  id,
  label: z.string(),
  fonts: z.object({ heading: fontSchema, body: fontSchema }),
  light: paletteSchema,
  dark: paletteSchema,
});

// ---------------------------------------------------------------------------------------------------------------
// game.json
// ---------------------------------------------------------------------------------------------------------------

export const iconRefSchema = z.object({ id, label: z.string(), icon: relPath });

export const ratingDefSchema = z.object({
  id,
  label: z.string(),
  description: richText,
  color: hexColor,
  colorblind: hexColor.describe('Replacement color used by the color-blind-safe palette option.'),
});

export const groupDefSchema = z.object({ id, label: z.string(), description: richText.optional() });

export const castingTypeSchema = z.object({ id, label: z.string(), description: richText });

export const statusDefSchema = z.object({
  id: z.enum(['core', 'expansion', 'playtest', 'legacy']),
  label: z.string(),
  description: z.string(),
});

export const artPackSchema = z.object({
  id,
  label: z.string(),
  kind: z.enum(['zip', 'directory']).describe('zip: a downloadable archive; directory: loose image files.'),
  url: z.url().optional().describe('Where users can download the pack. Never hotlinked by the engine.'),
  fileName: z.string().optional().describe('Expected archive file name, used to recognise the pack.'),
  license: z.string().describe('Short description of the terms the art is used under.'),
  credit: z.string().optional().describe('Artist credit line.'),
});

export const creditSchema = z.object({
  role: z.string(),
  names: z.array(z.string()).min(1),
  when: z
    .enum(['always', 'paizo-art', 'generic-art'])
    .default('always')
    .describe('Show this credit only for a particular art choice.'),
});

export const gameSchema = z.object({
  $schema: z.string().optional(),
  id,
  title: z.string().describe('Poster title, e.g. "Pathfinder 2e Classes".'),
  system: z.string().describe('Full game system name.'),
  shortName: z.string(),
  asOf: z.string().describe('Shown as "Accurate as of …".'),
  theme: relPath,
  attributes: z.array(iconRefSchema).min(1),
  traditions: z.array(iconRefSchema),
  ratings: z.array(ratingDefSchema).min(1),
  groups: z.array(groupDefSchema).min(1),
  castingTypes: z.array(castingTypeSchema),
  statuses: z.array(statusDefSchema),
  legend: z.object({
    howToUseTitle: z.string(),
    howToUse: richText,
    attributesTitle: z.string(),
    traditionsTitle: z.string(),
    castingTitle: z.string(),
    choiceTitle: z.string(),
    choice: richText,
    creditsTitle: z.string(),
  }),
  artPacks: z.array(artPackSchema),
  credits: z.array(creditSchema),
  notices: z.object({
    cup: richText.describe('Paizo Community Use Policy notice (required when Paizo material is shown).'),
    design: richText.describe('Credit for the original infographic design.'),
    license: richText.describe('License of this content.'),
  }),
  classes: z.array(relPath).min(1),
});

// ---------------------------------------------------------------------------------------------------------------
// classes/<id>.json
// ---------------------------------------------------------------------------------------------------------------

const ratingValue = z
  .number()
  .min(0)
  .max(5)
  .multipleOf(0.5)
  .describe('0 to 5 in steps of 0.5; half values draw a half square.');

export const ratingSchema = z.union([
  ratingValue,
  z
    .tuple([ratingValue, ratingValue])
    .refine(([lo, hi]) => lo < hi, 'range must be [low, high] with low < high')
    .describe('A range drawn with hatched squares: a fundamental choice moves the class between the two.'),
]);

export const featureSchema = z.object({ title: z.string().min(1), text: richText });

export const classSchema = z.object({
  $schema: z.string().optional(),
  id,
  name: z.string().min(1),
  status: z.enum(['core', 'expansion', 'playtest', 'legacy']),
  source: z.object({
    title: z.string(),
    date: yearMonth,
    url: z.url().optional(),
  }),
  group: id.describe('Id of one of the game groups.'),
  keyAttributes: z.array(id).min(1).describe('Attribute ids; more than one means "choose one".'),
  traditions: z.array(id).describe('Tradition ids the class can cast from; empty for non-casters.'),
  traditionsChosen: z
    .boolean()
    .default(false)
    .describe('True when the tradition is picked by subclass (all listed ones are possible).'),
  casting: id.nullable().describe('Casting type id, or null.'),
  hp: z.number().int().positive(),
  ratings: z.record(id, ratingSchema),
  features: z.array(featureSchema).min(1).max(3),
  iconic: z.object({ name: z.string(), ancestry: z.string().optional() }).optional(),
  art: z.object({
    emblem: relPath.describe('Generic SVG emblem drawn for this project.'),
    paizo: z
      .object({ pack: id, file: z.string().describe('Path of the image inside the art pack.') })
      .optional(),
    local: z.string().optional().describe('File name looked up in a locally supplied art folder.'),
  }),
  links: z.record(z.string(), z.url()).optional(),
});

export type Manifest = z.infer<typeof manifestSchema>;
export type ManifestFile = z.infer<typeof manifestFileSchema>;
export type Theme = z.infer<typeof themeSchema>;
export type Palette = z.infer<typeof paletteSchema>;
export type Game = z.infer<typeof gameSchema>;
export type ClassDef = z.infer<typeof classSchema>;
export type Rating = z.infer<typeof ratingSchema>;
export type ArtPack = z.infer<typeof artPackSchema>;
export type ClassStatus = ClassDef['status'];
